# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true #not used since Jekyll v3.0

# Setup
title:               Luc Geurts
tagline:             'Amazon Web Services, BunsenLabs Linux, Coding, Xperf'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
plugins: 			 [jekyll-paginate]
paginate:            5
paginate_path: 		 "page:num"

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
