# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true #not used since Jekyll v3.0

# Setup
title:               LUC GEURTS â€¢ Cloud, Linux, Xperf, Coding
tagline:             ''
description:         'Musings of a would be front-end web developer.'
url:                 http://lgeurts.github.io
baseurl:             ''
plugins: 			       [jekyll-paginate]
paginate:            6
paginate_path: 		   "page:num"

# About/contact
author:
  name:              Luc Geurts
  url:               https://twitter.com/lgeurts
  email:             luc.geurts@gmail.com

# Custom vars
version:             1.0.0
repo:                https://github.com/lgeurts/lgeurts.github.io
